config/routes.rb
Checklist::Application.routes.draw do
  get 'tasks/complete', to: 'tasks#complete'
  get 'tasks/autocomplete', to: 'tasks#autocomplete'
  get 'tags/:tag', to: 'tasks#index', as: :tag
  resources :tasks do
    resources :comments
  end
  root to: 'tasks#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  attr_accessible :body, :commenter
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :name, :finish_by, :content, :tag_list
  acts_as_taggable
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(params[:comment])
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to task_path(@task)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if params[:tag]
      @tasks = Task.tagged_with(params[:tag])
    else
      sleep 1
      @incomplete_tasks = Task.where(complete: false)
      @complete_tasks = Task.where(complete: true)
      @tasks = Task.find(:all, :order => "finish_by")
    end
  end

  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Post was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if params[:hard_button]
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    else @task.update_attributes!(params[:task])
      respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
      end
    end
  end

  def destroy
    @task = Task.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  def autocomplete
    @tasks = Task.all

    render json: @tasks.map(&:tag_list).uniq!.join(', ')
  end

  def complete
    if params[:tag]
      @tasks = Task.tagged_with(params[:tag])
    else
      sleep 1
      @incomplete_tasks = Task.where(complete: false)
      @complete_tasks = Task.where(complete: true)
      @tasks = Task.find(:all, :order => "finish_by")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_submit(text)
    link_to_function text, "$(this).closest('form').submit()"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>

<p>
  <b>Comment:</b>
  <%= simple_format comment.body %>
</p>
<p>
  <%= link_to 'Delete', [comment.task, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@task, @task.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :style => "width: 500pt;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Check List</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
<div class="field">
  <%= f.label :name, "Name:" %><br/>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br/>
  <%= f.text_field :tag_list, :id => "task_complete", :placeholder => 'Please use autocomplete, thanks.', data: { autocomplete_source: tasks_autocomplete_path } %>
</div>

<div class="field">
  <%= f.label :finish_by, "Should be finished by:" %><br/>
  <%= f.date_select(:finish_by, :order => [:day, :month, :year]) %>
</div>

<div>
  <%= f.label :content, "Description" %><br/>
  <%= f.text_area :content, :style => "width: 500pt; height: 250pt;" %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/tasks/_form_edit.html.erb
<%= form_for @task do |f| %>
<div class="field">
  <%= f.label :name, "Name:" %><br/>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br/>
  <%= f.text_field :tag_list, :id => "task_complete", :placeholder => 'Please use autocomplete, thanks.', data: { autocomplete_source: tasks_autocomplete_path } %>
</div>

<div class="field">
  <%= f.label :finish_by, "Should be finished by:" %><br/>
  <%= f.date_select(:finish_by, :order => [:day, :month, :year]) %>
</div>

<div>
  <%= f.label :content, "Description" %><br/>
  <%= f.text_area :content, :style => "width: 500pt; height: 250pt;" %>
</div>

<div class="actions">
  <%= link_to_submit "Update" %>
</div>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= f.label :complete, task.name %>
  <%= link_to "(remove)", task, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/tasks/complete.html.erb
<h1>Completed tasks</h1>

<%= link_to 'Home', tasks_path %><br/>
<hr />

<% @tasks.each do |task| %>
  <% if task.complete == true %>
    <div>
      <h2><%= link_to task.name, task %> (<%= task.finish_by.strftime("%d %B %Y") %>)</h2><br/>
      <i>(<%= truncate(task.content, :length => 50, :separator => ' ') %>)</i>
      <p>Tags: <%= raw task.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
      <hr />
    </div>
  <% end %>
<% end %>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/edit.html.erb
<h1>Edit that shit</h1>
<hr />

<%= render 'form_edit' %>

<%= link_to 'Back', @task %>

app/views/tasks/index.html.erb
<h1>Check List</h1>

<div id="tag_cloud">
  <% tag_cloud Task.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>
<hr /><br/>

<%= link_to "New Task", new_task_path %> |

<%= link_to 'Home', tasks_path %> |

<%= link_to 'Complete tasks', tasks_complete_path %>

<% if @incomplete_tasks.present? %>
  <h2>Incomplete Tasks</h2>
    <div class="tasks" id="incomplete_tasks">
      <%= render @incomplete_tasks %>
    </div>
<% end %>

<% if @complete_tasks.present? %>
  <h2>Complete Tasks</h2>
    <div class="tasks" id="complete_tasks">
      <%= render @complete_tasks %>
    </div>
<% end %>

<br/>
<h1>List of Tasks</h1>

<% @tasks.each do |task| %>
  <% if task.complete == false %>
    <div>
      <h2><%= link_to task.name, task %> (<%= task.finish_by.strftime("%d %B %Y") %>)</h2><br/>
      <i>(<%= truncate(task.content, :length => 50, :separator => ' ') %>)</i>
      <p>Tags: <%= raw task.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
      <hr />
    </div>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<p><%= link_to "Back to tasks", tasks_path %></p>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p>(Tags: <%= @task.tag_list %>)</p>
<hr />
<br/>
<p>
  Should be finished by:
  <%= @task.finish_by.strftime("%d %B %Y") unless @task.finish_by.nil? %>
</p>
<br/>
<p>
  Description:
  <%= simple_format @task.content %>
</p>

<br/>

<i><h2>Comments</h2></i>
  <%= render @task.comments %>

<br/>

<h2>Add a comment:</h2>
  <%= render "comments/form" %>

<br/>
<%= link_to 'Home', tasks_path %>|<%= link_to 'Edit', edit_task_path, :name => "hard_button" %>

app/views/tasks/update.js.erb
<% if @task.complete? %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>